/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CouncilRouteImport } from './routes/council'
import { Route as Df30RouteImport } from './routes/df30'
import { Route as Df30GlobalListRouteImport } from './routes/df30-global-list'
import { Route as Fr30RouteImport } from './routes/fr30'
import { Route as Fr30GlobalListRouteImport } from './routes/fr30-global-list'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as IntelRouteImport } from './routes/intel'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminDirectoryRouteImport } from './routes/admin.directory'
import { Route as AdminForecastRouteImport } from './routes/admin.forecast'
import { Route as AdminInsightsRouteImport } from './routes/admin.insights'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminPipelineRouteImport } from './routes/admin.pipeline'
import { Route as AdminTargetsRouteImport } from './routes/admin.targets'
import { Route as ForumsIndexRouteImport } from './routes/forums.index'
import { Route as ForumsAfricanMoneyMovementRouteImport } from './routes/forums.african-money-movement'
import { Route as ForumsFinancialRailsAfricaRouteImport } from './routes/forums.financial-rails-africa'
import { Route as ForumsFinancialRailsAsiaRouteImport } from './routes/forums.financial-rails-asia'
import { Route as ForumsFinancialRailsMenaRouteImport } from './routes/forums.financial-rails-mena'
import { Route as ForumsFinancialRailsV2RouteImport } from './routes/forums.financial-rails-v2'
import { Route as ForumsIndiaDigitalPaymentsRouteImport } from './routes/forums.india-digital-payments'
import { Route as ForumsMenaRouteImport } from './routes/forums.mena'
import { Route as AdminLeadsIndexRouteImport } from './routes/admin.leads.index'
import { Route as AdminLeadsIdRouteImport } from './routes/admin.leads.$id'
import { Route as AdminLeadsNewRouteImport } from './routes/admin.leads.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CouncilRoute = CouncilRouteImport.update({
  id: '/council',
  path: '/council',
  getParentRoute: () => rootRouteImport,
} as any)
const Df30Route = Df30RouteImport.update({
  id: '/df30',
  path: '/df30',
  getParentRoute: () => rootRouteImport,
} as any)
const Df30GlobalListRoute = Df30GlobalListRouteImport.update({
  id: '/df30-global-list',
  path: '/df30-global-list',
  getParentRoute: () => rootRouteImport,
} as any)
const Fr30Route = Fr30RouteImport.update({
  id: '/fr30',
  path: '/fr30',
  getParentRoute: () => rootRouteImport,
} as any)
const Fr30GlobalListRoute = Fr30GlobalListRouteImport.update({
  id: '/fr30-global-list',
  path: '/fr30-global-list',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelRoute = IntelRouteImport.update({
  id: '/intel',
  path: '/intel',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRoute = IntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDirectoryRoute = AdminDirectoryRouteImport.update({
  id: '/admin/directory',
  path: '/admin/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminForecastRoute = AdminForecastRouteImport.update({
  id: '/admin/forecast',
  path: '/admin/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInsightsRoute = AdminInsightsRouteImport.update({
  id: '/admin/insights',
  path: '/admin/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPipelineRoute = AdminPipelineRouteImport.update({
  id: '/admin/pipeline',
  path: '/admin/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTargetsRoute = AdminTargetsRouteImport.update({
  id: '/admin/targets',
  path: '/admin/targets',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumsIndexRoute = ForumsIndexRouteImport.update({
  id: '/forums/',
  path: '/forums/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumsAfricanMoneyMovementRoute =
  ForumsAfricanMoneyMovementRouteImport.update({
    id: '/forums/african-money-movement',
    path: '/forums/african-money-movement',
    getParentRoute: () => rootRouteImport,
  } as any)
const ForumsFinancialRailsAfricaRoute =
  ForumsFinancialRailsAfricaRouteImport.update({
    id: '/forums/financial-rails-africa',
    path: '/forums/financial-rails-africa',
    getParentRoute: () => rootRouteImport,
  } as any)
const ForumsFinancialRailsAsiaRoute =
  ForumsFinancialRailsAsiaRouteImport.update({
    id: '/forums/financial-rails-asia',
    path: '/forums/financial-rails-asia',
    getParentRoute: () => rootRouteImport,
  } as any)
const ForumsFinancialRailsMenaRoute =
  ForumsFinancialRailsMenaRouteImport.update({
    id: '/forums/financial-rails-mena',
    path: '/forums/financial-rails-mena',
    getParentRoute: () => rootRouteImport,
  } as any)
const ForumsFinancialRailsV2Route = ForumsFinancialRailsV2RouteImport.update({
  id: '/forums/financial-rails-v2',
  path: '/forums/financial-rails-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumsIndiaDigitalPaymentsRoute =
  ForumsIndiaDigitalPaymentsRouteImport.update({
    id: '/forums/india-digital-payments',
    path: '/forums/india-digital-payments',
    getParentRoute: () => rootRouteImport,
  } as any)
const ForumsMenaRoute = ForumsMenaRouteImport.update({
  id: '/forums/mena',
  path: '/forums/mena',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsIndexRoute = AdminLeadsIndexRouteImport.update({
  id: '/admin/leads/',
  path: '/admin/leads/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsIdRoute = AdminLeadsIdRouteImport.update({
  id: '/admin/leads/$id',
  path: '/admin/leads/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsNewRoute = AdminLeadsNewRouteImport.update({
  id: '/admin/leads/new',
  path: '/admin/leads/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/council': typeof CouncilRoute
  '/df30': typeof Df30Route
  '/df30-global-list': typeof Df30GlobalListRoute
  '/fr30': typeof Fr30Route
  '/fr30-global-list': typeof Fr30GlobalListRoute
  '/insights': typeof InsightsRoute
  '/intel': typeof IntelRoute
  '/intelligence': typeof IntelligenceRoute
  '/partners': typeof PartnersRoute
  '/admin/directory': typeof AdminDirectoryRoute
  '/admin/forecast': typeof AdminForecastRoute
  '/admin/insights': typeof AdminInsightsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/targets': typeof AdminTargetsRoute
  '/forums/african-money-movement': typeof ForumsAfricanMoneyMovementRoute
  '/forums/financial-rails-africa': typeof ForumsFinancialRailsAfricaRoute
  '/forums/financial-rails-asia': typeof ForumsFinancialRailsAsiaRoute
  '/forums/financial-rails-mena': typeof ForumsFinancialRailsMenaRoute
  '/forums/financial-rails-v2': typeof ForumsFinancialRailsV2Route
  '/forums/india-digital-payments': typeof ForumsIndiaDigitalPaymentsRoute
  '/forums/mena': typeof ForumsMenaRoute
  '/admin/': typeof AdminIndexRoute
  '/forums/': typeof ForumsIndexRoute
  '/admin/leads/$id': typeof AdminLeadsIdRoute
  '/admin/leads/new': typeof AdminLeadsNewRoute
  '/admin/leads/': typeof AdminLeadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/council': typeof CouncilRoute
  '/df30': typeof Df30Route
  '/df30-global-list': typeof Df30GlobalListRoute
  '/fr30': typeof Fr30Route
  '/fr30-global-list': typeof Fr30GlobalListRoute
  '/insights': typeof InsightsRoute
  '/intel': typeof IntelRoute
  '/intelligence': typeof IntelligenceRoute
  '/partners': typeof PartnersRoute
  '/admin/directory': typeof AdminDirectoryRoute
  '/admin/forecast': typeof AdminForecastRoute
  '/admin/insights': typeof AdminInsightsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/targets': typeof AdminTargetsRoute
  '/forums/african-money-movement': typeof ForumsAfricanMoneyMovementRoute
  '/forums/financial-rails-africa': typeof ForumsFinancialRailsAfricaRoute
  '/forums/financial-rails-asia': typeof ForumsFinancialRailsAsiaRoute
  '/forums/financial-rails-mena': typeof ForumsFinancialRailsMenaRoute
  '/forums/financial-rails-v2': typeof ForumsFinancialRailsV2Route
  '/forums/india-digital-payments': typeof ForumsIndiaDigitalPaymentsRoute
  '/forums/mena': typeof ForumsMenaRoute
  '/admin': typeof AdminIndexRoute
  '/forums': typeof ForumsIndexRoute
  '/admin/leads/$id': typeof AdminLeadsIdRoute
  '/admin/leads/new': typeof AdminLeadsNewRoute
  '/admin/leads': typeof AdminLeadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/council': typeof CouncilRoute
  '/df30': typeof Df30Route
  '/df30-global-list': typeof Df30GlobalListRoute
  '/fr30': typeof Fr30Route
  '/fr30-global-list': typeof Fr30GlobalListRoute
  '/insights': typeof InsightsRoute
  '/intel': typeof IntelRoute
  '/intelligence': typeof IntelligenceRoute
  '/partners': typeof PartnersRoute
  '/admin/directory': typeof AdminDirectoryRoute
  '/admin/forecast': typeof AdminForecastRoute
  '/admin/insights': typeof AdminInsightsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/targets': typeof AdminTargetsRoute
  '/forums/african-money-movement': typeof ForumsAfricanMoneyMovementRoute
  '/forums/financial-rails-africa': typeof ForumsFinancialRailsAfricaRoute
  '/forums/financial-rails-asia': typeof ForumsFinancialRailsAsiaRoute
  '/forums/financial-rails-mena': typeof ForumsFinancialRailsMenaRoute
  '/forums/financial-rails-v2': typeof ForumsFinancialRailsV2Route
  '/forums/india-digital-payments': typeof ForumsIndiaDigitalPaymentsRoute
  '/forums/mena': typeof ForumsMenaRoute
  '/admin/': typeof AdminIndexRoute
  '/forums/': typeof ForumsIndexRoute
  '/admin/leads/$id': typeof AdminLeadsIdRoute
  '/admin/leads/new': typeof AdminLeadsNewRoute
  '/admin/leads/': typeof AdminLeadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/council'
    | '/df30'
    | '/df30-global-list'
    | '/fr30'
    | '/fr30-global-list'
    | '/insights'
    | '/intel'
    | '/intelligence'
    | '/partners'
    | '/admin/directory'
    | '/admin/forecast'
    | '/admin/insights'
    | '/admin/login'
    | '/admin/pipeline'
    | '/admin/targets'
    | '/forums/african-money-movement'
    | '/forums/financial-rails-africa'
    | '/forums/financial-rails-asia'
    | '/forums/financial-rails-mena'
    | '/forums/financial-rails-v2'
    | '/forums/india-digital-payments'
    | '/forums/mena'
    | '/admin/'
    | '/forums/'
    | '/admin/leads/$id'
    | '/admin/leads/new'
    | '/admin/leads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/council'
    | '/df30'
    | '/df30-global-list'
    | '/fr30'
    | '/fr30-global-list'
    | '/insights'
    | '/intel'
    | '/intelligence'
    | '/partners'
    | '/admin/directory'
    | '/admin/forecast'
    | '/admin/insights'
    | '/admin/login'
    | '/admin/pipeline'
    | '/admin/targets'
    | '/forums/african-money-movement'
    | '/forums/financial-rails-africa'
    | '/forums/financial-rails-asia'
    | '/forums/financial-rails-mena'
    | '/forums/financial-rails-v2'
    | '/forums/india-digital-payments'
    | '/forums/mena'
    | '/admin'
    | '/forums'
    | '/admin/leads/$id'
    | '/admin/leads/new'
    | '/admin/leads'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/council'
    | '/df30'
    | '/df30-global-list'
    | '/fr30'
    | '/fr30-global-list'
    | '/insights'
    | '/intel'
    | '/intelligence'
    | '/partners'
    | '/admin/directory'
    | '/admin/forecast'
    | '/admin/insights'
    | '/admin/login'
    | '/admin/pipeline'
    | '/admin/targets'
    | '/forums/african-money-movement'
    | '/forums/financial-rails-africa'
    | '/forums/financial-rails-asia'
    | '/forums/financial-rails-mena'
    | '/forums/financial-rails-v2'
    | '/forums/india-digital-payments'
    | '/forums/mena'
    | '/admin/'
    | '/forums/'
    | '/admin/leads/$id'
    | '/admin/leads/new'
    | '/admin/leads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CouncilRoute: typeof CouncilRoute
  Df30Route: typeof Df30Route
  Df30GlobalListRoute: typeof Df30GlobalListRoute
  Fr30Route: typeof Fr30Route
  Fr30GlobalListRoute: typeof Fr30GlobalListRoute
  InsightsRoute: typeof InsightsRoute
  IntelRoute: typeof IntelRoute
  IntelligenceRoute: typeof IntelligenceRoute
  PartnersRoute: typeof PartnersRoute
  AdminDirectoryRoute: typeof AdminDirectoryRoute
  AdminForecastRoute: typeof AdminForecastRoute
  AdminInsightsRoute: typeof AdminInsightsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPipelineRoute: typeof AdminPipelineRoute
  AdminTargetsRoute: typeof AdminTargetsRoute
  ForumsAfricanMoneyMovementRoute: typeof ForumsAfricanMoneyMovementRoute
  ForumsFinancialRailsAfricaRoute: typeof ForumsFinancialRailsAfricaRoute
  ForumsFinancialRailsAsiaRoute: typeof ForumsFinancialRailsAsiaRoute
  ForumsFinancialRailsMenaRoute: typeof ForumsFinancialRailsMenaRoute
  ForumsFinancialRailsV2Route: typeof ForumsFinancialRailsV2Route
  ForumsIndiaDigitalPaymentsRoute: typeof ForumsIndiaDigitalPaymentsRoute
  ForumsMenaRoute: typeof ForumsMenaRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ForumsIndexRoute: typeof ForumsIndexRoute
  AdminLeadsIdRoute: typeof AdminLeadsIdRoute
  AdminLeadsNewRoute: typeof AdminLeadsNewRoute
  AdminLeadsIndexRoute: typeof AdminLeadsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/council': {
      id: '/council'
      path: '/council'
      fullPath: '/council'
      preLoaderRoute: typeof CouncilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/df30': {
      id: '/df30'
      path: '/df30'
      fullPath: '/df30'
      preLoaderRoute: typeof Df30RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/df30-global-list': {
      id: '/df30-global-list'
      path: '/df30-global-list'
      fullPath: '/df30-global-list'
      preLoaderRoute: typeof Df30GlobalListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr30': {
      id: '/fr30'
      path: '/fr30'
      fullPath: '/fr30'
      preLoaderRoute: typeof Fr30RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr30-global-list': {
      id: '/fr30-global-list'
      path: '/fr30-global-list'
      fullPath: '/fr30-global-list'
      preLoaderRoute: typeof Fr30GlobalListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intel': {
      id: '/intel'
      path: '/intel'
      fullPath: '/intel'
      preLoaderRoute: typeof IntelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence': {
      id: '/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof IntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/directory': {
      id: '/admin/directory'
      path: '/admin/directory'
      fullPath: '/admin/directory'
      preLoaderRoute: typeof AdminDirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/forecast': {
      id: '/admin/forecast'
      path: '/admin/forecast'
      fullPath: '/admin/forecast'
      preLoaderRoute: typeof AdminForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/insights': {
      id: '/admin/insights'
      path: '/admin/insights'
      fullPath: '/admin/insights'
      preLoaderRoute: typeof AdminInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pipeline': {
      id: '/admin/pipeline'
      path: '/admin/pipeline'
      fullPath: '/admin/pipeline'
      preLoaderRoute: typeof AdminPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/targets': {
      id: '/admin/targets'
      path: '/admin/targets'
      fullPath: '/admin/targets'
      preLoaderRoute: typeof AdminTargetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forums/': {
      id: '/forums/'
      path: '/forums'
      fullPath: '/forums/'
      preLoaderRoute: typeof ForumsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forums/african-money-movement': {
      id: '/forums/african-money-movement'
      path: '/forums/african-money-movement'
      fullPath: '/forums/african-money-movement'
      preLoaderRoute: typeof ForumsAfricanMoneyMovementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forums/financial-rails-africa': {
      id: '/forums/financial-rails-africa'
      path: '/forums/financial-rails-africa'
      fullPath: '/forums/financial-rails-africa'
      preLoaderRoute: typeof ForumsFinancialRailsAfricaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forums/financial-rails-asia': {
      id: '/forums/financial-rails-asia'
      path: '/forums/financial-rails-asia'
      fullPath: '/forums/financial-rails-asia'
      preLoaderRoute: typeof ForumsFinancialRailsAsiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forums/financial-rails-mena': {
      id: '/forums/financial-rails-mena'
      path: '/forums/financial-rails-mena'
      fullPath: '/forums/financial-rails-mena'
      preLoaderRoute: typeof ForumsFinancialRailsMenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forums/financial-rails-v2': {
      id: '/forums/financial-rails-v2'
      path: '/forums/financial-rails-v2'
      fullPath: '/forums/financial-rails-v2'
      preLoaderRoute: typeof ForumsFinancialRailsV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forums/india-digital-payments': {
      id: '/forums/india-digital-payments'
      path: '/forums/india-digital-payments'
      fullPath: '/forums/india-digital-payments'
      preLoaderRoute: typeof ForumsIndiaDigitalPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forums/mena': {
      id: '/forums/mena'
      path: '/forums/mena'
      fullPath: '/forums/mena'
      preLoaderRoute: typeof ForumsMenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads/': {
      id: '/admin/leads/'
      path: '/admin/leads'
      fullPath: '/admin/leads/'
      preLoaderRoute: typeof AdminLeadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads/$id': {
      id: '/admin/leads/$id'
      path: '/admin/leads/$id'
      fullPath: '/admin/leads/$id'
      preLoaderRoute: typeof AdminLeadsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads/new': {
      id: '/admin/leads/new'
      path: '/admin/leads/new'
      fullPath: '/admin/leads/new'
      preLoaderRoute: typeof AdminLeadsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CouncilRoute: CouncilRoute,
  Df30Route: Df30Route,
  Df30GlobalListRoute: Df30GlobalListRoute,
  Fr30Route: Fr30Route,
  Fr30GlobalListRoute: Fr30GlobalListRoute,
  InsightsRoute: InsightsRoute,
  IntelRoute: IntelRoute,
  IntelligenceRoute: IntelligenceRoute,
  PartnersRoute: PartnersRoute,
  AdminDirectoryRoute: AdminDirectoryRoute,
  AdminForecastRoute: AdminForecastRoute,
  AdminInsightsRoute: AdminInsightsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPipelineRoute: AdminPipelineRoute,
  AdminTargetsRoute: AdminTargetsRoute,
  ForumsAfricanMoneyMovementRoute: ForumsAfricanMoneyMovementRoute,
  ForumsFinancialRailsAfricaRoute: ForumsFinancialRailsAfricaRoute,
  ForumsFinancialRailsAsiaRoute: ForumsFinancialRailsAsiaRoute,
  ForumsFinancialRailsMenaRoute: ForumsFinancialRailsMenaRoute,
  ForumsFinancialRailsV2Route: ForumsFinancialRailsV2Route,
  ForumsIndiaDigitalPaymentsRoute: ForumsIndiaDigitalPaymentsRoute,
  ForumsMenaRoute: ForumsMenaRoute,
  AdminIndexRoute: AdminIndexRoute,
  ForumsIndexRoute: ForumsIndexRoute,
  AdminLeadsIdRoute: AdminLeadsIdRoute,
  AdminLeadsNewRoute: AdminLeadsNewRoute,
  AdminLeadsIndexRoute: AdminLeadsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
