/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CouncilRouteImport } from './routes/council'
import { Route as Df30RouteImport } from './routes/df30'
import { Route as Df30GlobalListRouteImport } from './routes/df30-global-list'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as IntelRouteImport } from './routes/intel'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as ForumsIndexRouteImport } from './routes/forums.index'
import { Route as ForumsAfricanMoneyMovementRouteImport } from './routes/forums.african-money-movement'
import { Route as ForumsFinancialRailsV2RouteImport } from './routes/forums.financial-rails-v2'
import { Route as ForumsIndiaDigitalPaymentsRouteImport } from './routes/forums.india-digital-payments'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CouncilRoute = CouncilRouteImport.update({
  id: '/council',
  path: '/council',
  getParentRoute: () => rootRouteImport,
} as any)
const Df30Route = Df30RouteImport.update({
  id: '/df30',
  path: '/df30',
  getParentRoute: () => rootRouteImport,
} as any)
const Df30GlobalListRoute = Df30GlobalListRouteImport.update({
  id: '/df30-global-list',
  path: '/df30-global-list',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelRoute = IntelRouteImport.update({
  id: '/intel',
  path: '/intel',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumsIndexRoute = ForumsIndexRouteImport.update({
  id: '/forums/',
  path: '/forums/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumsAfricanMoneyMovementRoute =
  ForumsAfricanMoneyMovementRouteImport.update({
    id: '/forums/african-money-movement',
    path: '/forums/african-money-movement',
    getParentRoute: () => rootRouteImport,
  } as any)
const ForumsFinancialRailsV2Route = ForumsFinancialRailsV2RouteImport.update({
  id: '/forums/financial-rails-v2',
  path: '/forums/financial-rails-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumsIndiaDigitalPaymentsRoute =
  ForumsIndiaDigitalPaymentsRouteImport.update({
    id: '/forums/india-digital-payments',
    path: '/forums/india-digital-payments',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/council': typeof CouncilRoute
  '/df30': typeof Df30Route
  '/df30-global-list': typeof Df30GlobalListRoute
  '/insights': typeof InsightsRoute
  '/intel': typeof IntelRoute
  '/partners': typeof PartnersRoute
  '/forums/african-money-movement': typeof ForumsAfricanMoneyMovementRoute
  '/forums/financial-rails-v2': typeof ForumsFinancialRailsV2Route
  '/forums/india-digital-payments': typeof ForumsIndiaDigitalPaymentsRoute
  '/forums/': typeof ForumsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/council': typeof CouncilRoute
  '/df30': typeof Df30Route
  '/df30-global-list': typeof Df30GlobalListRoute
  '/insights': typeof InsightsRoute
  '/intel': typeof IntelRoute
  '/partners': typeof PartnersRoute
  '/forums/african-money-movement': typeof ForumsAfricanMoneyMovementRoute
  '/forums/financial-rails-v2': typeof ForumsFinancialRailsV2Route
  '/forums/india-digital-payments': typeof ForumsIndiaDigitalPaymentsRoute
  '/forums': typeof ForumsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/council': typeof CouncilRoute
  '/df30': typeof Df30Route
  '/df30-global-list': typeof Df30GlobalListRoute
  '/insights': typeof InsightsRoute
  '/intel': typeof IntelRoute
  '/partners': typeof PartnersRoute
  '/forums/african-money-movement': typeof ForumsAfricanMoneyMovementRoute
  '/forums/financial-rails-v2': typeof ForumsFinancialRailsV2Route
  '/forums/india-digital-payments': typeof ForumsIndiaDigitalPaymentsRoute
  '/forums/': typeof ForumsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/council'
    | '/df30'
    | '/df30-global-list'
    | '/insights'
    | '/intel'
    | '/partners'
    | '/forums/african-money-movement'
    | '/forums/financial-rails-v2'
    | '/forums/india-digital-payments'
    | '/forums/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/council'
    | '/df30'
    | '/df30-global-list'
    | '/insights'
    | '/intel'
    | '/partners'
    | '/forums/african-money-movement'
    | '/forums/financial-rails-v2'
    | '/forums/india-digital-payments'
    | '/forums'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/council'
    | '/df30'
    | '/df30-global-list'
    | '/insights'
    | '/intel'
    | '/partners'
    | '/forums/african-money-movement'
    | '/forums/financial-rails-v2'
    | '/forums/india-digital-payments'
    | '/forums/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CouncilRoute: typeof CouncilRoute
  Df30Route: typeof Df30Route
  Df30GlobalListRoute: typeof Df30GlobalListRoute
  InsightsRoute: typeof InsightsRoute
  IntelRoute: typeof IntelRoute
  PartnersRoute: typeof PartnersRoute
  ForumsAfricanMoneyMovementRoute: typeof ForumsAfricanMoneyMovementRoute
  ForumsFinancialRailsV2Route: typeof ForumsFinancialRailsV2Route
  ForumsIndiaDigitalPaymentsRoute: typeof ForumsIndiaDigitalPaymentsRoute
  ForumsIndexRoute: typeof ForumsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/council': {
      id: '/council'
      path: '/council'
      fullPath: '/council'
      preLoaderRoute: typeof CouncilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/df30': {
      id: '/df30'
      path: '/df30'
      fullPath: '/df30'
      preLoaderRoute: typeof Df30RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/df30-global-list': {
      id: '/df30-global-list'
      path: '/df30-global-list'
      fullPath: '/df30-global-list'
      preLoaderRoute: typeof Df30GlobalListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intel': {
      id: '/intel'
      path: '/intel'
      fullPath: '/intel'
      preLoaderRoute: typeof IntelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forums/': {
      id: '/forums/'
      path: '/forums'
      fullPath: '/forums/'
      preLoaderRoute: typeof ForumsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forums/african-money-movement': {
      id: '/forums/african-money-movement'
      path: '/forums/african-money-movement'
      fullPath: '/forums/african-money-movement'
      preLoaderRoute: typeof ForumsAfricanMoneyMovementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forums/financial-rails-v2': {
      id: '/forums/financial-rails-v2'
      path: '/forums/financial-rails-v2'
      fullPath: '/forums/financial-rails-v2'
      preLoaderRoute: typeof ForumsFinancialRailsV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forums/india-digital-payments': {
      id: '/forums/india-digital-payments'
      path: '/forums/india-digital-payments'
      fullPath: '/forums/india-digital-payments'
      preLoaderRoute: typeof ForumsIndiaDigitalPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CouncilRoute: CouncilRoute,
  Df30Route: Df30Route,
  Df30GlobalListRoute: Df30GlobalListRoute,
  InsightsRoute: InsightsRoute,
  IntelRoute: IntelRoute,
  PartnersRoute: PartnersRoute,
  ForumsAfricanMoneyMovementRoute: ForumsAfricanMoneyMovementRoute,
  ForumsFinancialRailsV2Route: ForumsFinancialRailsV2Route,
  ForumsIndiaDigitalPaymentsRoute: ForumsIndiaDigitalPaymentsRoute,
  ForumsIndexRoute: ForumsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
